#!/bin/bash
# /etc/init.d/camera-monitor

### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in
    start)
        echo "Starting camera monitor"
        forever start /home/pi/camera/monitor.js
        ;;
    stop)
        echo "Stopping camera monitor"
        forever stopall
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

forever start /home/pi/camera/monitor.js

exit 0
